//! Comment

pub mod field;

use crate::message::field::{
    Field,
    value::{begin_string::BeginString, msg_type::MsgType},
};

/// Comment
pub struct Header {
    /// Comment
    begin_string: BeginString,

    /// Comment
    msg_type: MsgType,

    /// Comment
    fields: Option<Vec<Field>>,
}

/// Comment
pub struct Message {
    /// Comment
    header: Header,

    /// Comment
    body: Vec<Field>,
}

impl Message {
    /// Comment
    #[must_use]
    pub fn builder(begin_string: BeginString, msg_type: MsgType) -> MessageBuilder<false> {
        let header = Header {
            begin_string,
            msg_type,
            fields: None,
        };

        MessageBuilder {
            inner: Message {
                header,
                body: Vec::new(),
            },
        }
    }
}

/// Comment
pub struct MessageBuilder<const IS_INIT: bool> {
    /// Comment
    inner: Message,
}

impl<const IS_INIT: bool> MessageBuilder<IS_INIT> {
    /// Comment
    #[must_use]
    pub fn header(mut self, field: Field) -> Self {
        if let Some(fields) = &mut self.inner.header.fields {
            fields.push(field);
        } else {
            self.inner.header.fields = Some(Vec::new());
            return self.header(field);
        }

        self
    }

    /// Comment
    #[must_use]
    pub fn field(mut self, field: Field) -> MessageBuilder<true> {
        self.inner.body.push(field);

        MessageBuilder { inner: self.inner }
    }
}

impl MessageBuilder<true> {
    /// Comment
    #[must_use]
    pub fn build(self) -> Message {
        self.inner
    }
}

#[cfg(test)]
mod test {
    use crate::message::{
        Message,
        field::{
            Field,
            value::{begin_string::BeginString, msg_type::MsgType},
        },
    };

    #[test]
    fn basic_builder() {
        let builder = Message::builder(BeginString::FIX44, MsgType::Logon);

        let custom_field = Field::Custom {
            tag: 40000,
            value: b"custom_field".to_vec(),
        };

        let msg = builder.field(custom_field.clone()).build();

        // header
        assert_eq!(msg.header.begin_string, BeginString::FIX44);
        assert_eq!(msg.header.msg_type, MsgType::Logon);

        // body
        assert_eq!(msg.body[0], custom_field);
    }

    #[test]
    fn body_length() {
        let builder = Message::builder(BeginString::FIX44, MsgType::Logout);

        let custom_field = Field::Custom {
            tag: 40000,
            value: b"custom_field".to_vec(),
        };

        let msg = builder.field(custom_field.clone()).build();

        // header
        assert_eq!(msg.header.begin_string, BeginString::FIX44);
        assert_eq!(msg.header.msg_type, MsgType::Logout);

        // autogenerated header
        // assert_eq!(msg.header.body_length, 0);

        // body
        assert_eq!(msg.body[0], custom_field);
    }
}
